# pdf_utils.py
import os
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, PageBreak, Image
from reportlab.lib import colors

from graphviz import Digraph

def create_arch_diagram(parsed_structure, out_path="arch_diagram.png"):
    """Generate architecture diagram as PNG using Graphviz."""
    try:
        dot = Digraph(format='png')
        dot.attr(rankdir='LR')
        dot.node("Codebase", shape="box", style="filled", color="lightblue")

        # Add imports
        for im in parsed_structure.get("imports", [])[:20]:
            dot.node(f"imp_{im}", im, shape="ellipse")
            dot.edge("Codebase", f"imp_{im}")

        # Classes
        for cls in parsed_structure.get("classes", [])[:15]:
            name = cls.get("name", "")
            dot.node(f"cls_{name}", f"Class: {name}", shape="box")
            dot.edge("Codebase", f"cls_{name}")

        # Functions
        for fn in parsed_structure.get("functions", [])[:20]:
            name = fn.get("name", "")
            dot.node(f"fn_{name}", f"fn: {name}()", shape="note")
            dot.edge("Codebase", f"fn_{name}")

        dot.render(filename=out_path.replace(".png", ""), cleanup=True)

        if os.path.exists(out_path):
            return out_path
        if os.path.exists(out_path.replace(".png", "") + ".png"):
            return out_path.replace(".png", "") + ".png"

    except Exception as e:
        print("Graphviz Error:", e)

    return None


def create_pdf_from_markdown(markdown_text, parsed_structure, diagram_path=None, filename="documentation.pdf"):
    """Generate professional PDF without using TableOfContents."""
    try:
        doc = SimpleDocTemplate(filename, pagesize=A4,
                                rightMargin=50, leftMargin=50,
                                topMargin=50, bottomMargin=50)

        styles = getSampleStyleSheet()
        story = []

        # --- Cover Page ---
        story.append(Paragraph("<b>AI-Powered Technical Documentation System</b>", styles['Title']))
        story.append(Spacer(1, 20))
        story.append(Paragraph("Automated Documentation Generated by AutoDoc AI", styles['Heading2']))
        story.append(Spacer(1, 40))
        story.append(Paragraph("This document was generated automatically from the uploaded source code.", styles['Normal']))
        story.append(PageBreak())

        # --- Manual TOC Page ---
        story.append(Paragraph("<b>Table of Contents</b>", styles['Heading1']))
        story.append(Spacer(1, 12))

        toc_items = [
            "1. Architecture Diagram",
            "2. Documentation Overview",
            "3. Classes",
            "4. Functions",
            "5. Imports",
            "6. Additional Notes"
        ]

        for item in toc_items:
            story.append(Paragraph(item, styles['Normal']))
            story.append(Spacer(1, 6))

        story.append(PageBreak())

        # --- Architecture Diagram ---
        if diagram_path and os.path.exists(diagram_path):
            story.append(Paragraph("Architecture Diagram", styles['Heading1']))
            story.append(Spacer(1, 12))
            story.append(Image(diagram_path, width=5.5*inch, height=3.5*inch))
            story.append(PageBreak())

        # --- Markdown Conversion (Simple) ---
        lines = markdown_text.splitlines()
        for line in lines:
            if line.startswith("# "):
                story.append(Paragraph(line[2:], styles['Heading1']))
            elif line.startswith("## "):
                story.append(Paragraph(line[3:], styles['Heading2']))
            elif line.startswith("### "):
                story.append(Paragraph(line[4:], styles['Heading3']))
            elif line.strip():
                story.append(Paragraph(line, styles['Normal']))
            story.append(Spacer(1, 6))

        doc.build(story)
        return filename

    except Exception as e:
        print("PDF Error:", e)
        return None
